export interface GameData {
  adjustmentsDay: string;
  adjustmentsSpan: number;
  adjustmentsTime: Date;
  administrators: any[];
  assignmentMethod: string;
  assignments: any[];
  blindAdministrators: boolean;
  concurrentGamesLimit: number;
  currentYear: number;
  deadlineType: string;
  displayAsAdmin: boolean;
  finalReadinessCheck: boolean;
  gameName: string;
  gameStatus: string;
  gameTimeZone: number;
  hiddenGame: boolean;
  nmrToleranceAdjustments: boolean | null;
  nmrToleranceOrders: boolean | null;
  nmrToleranceRetreats: boolean | null;
  nmrToleranceTotal: number;
  nominationsDay: string;
  nominationsSpan: number;
  nominationsTime: Date;
  observeDst: boolean;
  ordersDay: string;
  ordersSpan: number;
  ordersTime: Date;
  partialRosterStart: boolean;
  privateGame: boolean;
  retreatsDay: string;
  retreatsSpan: number;
  retreatsTime: Date;
  rules: any[];
  startTime: Date;
  stylizedStartYear: number;
  timeCreated: Date;
  turn1Timing: string;
  voteDelayCount: number | null;
  voteDelayDisplayCount: number | null;
  voteDelayDisplayPercent: number | null;
  voteDelayEnabled: boolean;
  voteDelayLock: number | null;
  voteDelayPercent: number | null;
  votesDay: string;
  votesSpan: number;
  votesTime: Date;
  nominationTiming: string;
  nominationYear: number;
  automaticAssignments: boolean;
  ratingLimitsEnabled: boolean;
  funMin: number;
  funMax: number;
  skillMin: number;
  skillMax: number;
};